version: '3.8'

services:
  app:
    build: .
    ports:
      - "9999:9999"
    networks:
      - app-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - "C:/mongo_data:/data/db"
    networks:
      - app-network

networks:
  app-network: